# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/muirmap',
                'doc_host': 'https://aliceheiman.github.io',
                'git_url': 'https://github.com/aliceheiman/muirmap',
                'lib_path': 'muirmap'},
  'syms': {'muirmap.core': {'muirmap.core.foo': ('core.html#foo', 'muirmap/core.py')}}}
